version: '2'

services:
  web:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3002:3002'
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/db
